name: 01 - Building Blocks
on: 
  - push
  - workflow_dispatch

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Say Hello"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps: 
      - name: Failed Step
        run: |
          "I will fail"
      - name: Say Goodbye
        run: echo "GoodBye"
        