name: 08 - Variables
on: 
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am workflow env var"
  OVERWRITTEN_VAR: "I will be overwritten"


jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job var"
      OVERWRITTEN: "I will be overwritten"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am step var"
          step_var2: "I am another step var"
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var:$step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten: ${{ env.OVERWRITTEN}}"
      - name: Overwrite job Variable
        env:
          OVERWRITTEN: "I have been overwritten at the step level"
        run: |  
          echo "step env var: $OVERWRITTEN"
  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
          echo "Repo var: ${{ vars.REPOSITORY_VAR }}"
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print Prod Variables
        run: |
          echo "Repo var: ${{ vars.REPOSITORY_VAR }}"
          echo "Environment var: ${{ vars.TARGET_VAR }}"
  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print Undefined Variables
        run: | 
          echo "Org var: ${{ vars.UNDEFINED_VAR || 'default value' }} "