name: 08 - Variables
on: 
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am workflow env var"
  OVERWRITTEN_VAR: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job var"
      OVERWRITTEN: "I will be overwritten"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am step var"
          step_var2: "I am another step var"
        run: |
          echo "Step env var: ${{ env.STEP_VAR}}"
          echo "Step env var:${{ env.step_var2}}"
          echo "Job env var: ${{ env.JOB_VAR}}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR}}"
          echo "Overwritten: ${{ env.OVERWRITTEN}}"
      - name: Overwrite job Variable
        env:
          OVERWRITTEN: "I have been overwritten at the step level"
        run: |
          echo "step env var: ${{ env.OVERWRITTEN}}"